[package]
name = "gold_tracker"
description = "A CLI tool to keep track of your D&D currency."
license = "MIT"
version = "0.1.2"
authors = ["Dax ğŸ° <limeside@gmail.com>"]
edition = "2018"

[dependencies]
